### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by ahvdesign** [jsnee/vscode-dmbinder#11]
Hello,

On a fresh installation of the extension, attempting to do anything results in a 'command 'dmbinder.xxxxx.xxxxxx' not found' message. For example:

- command 'dmbinder.source.addFile' not found
- command 'dmbinder.source.addFolder' not found
- command 'dmbinder.campaign.refresh' not found
- command 'dmbinder.component.addFile' not found

I have attempted this on multiple computers. Also tried to manually create a campaign.json file using the example in the wiki and created the folder structure for it. I can't seem to get any commands to work. Is there something I could be missing?

**Comment by jsnee** [comment]
The problem, most likely is that the commands won't work until the extension is loaded. To avoid unnecessary load on your system when you're not working on campaign documents, I made it so that the extension really only loads when the config file is in the correct place (there are a few other times, but this is the main one). To get your config file setup correctly, try running this command:
![image](https://user-images.githubusercontent.com/2386345/71756382-1d7c3a80-2e55-11ea-9210-a5ba7c5f3daa.png)

**Comment by ahvdesign** [comment]
That did it! Thank you for the quick response.

**Comment by jsnee** [comment]
No problem! I should update the documentation to make that more clear.
