### ISSUE TITLE
Customizing css for rendering

### ISSUE THREAD

**Issue by Grimo0** [jsnee/vscode-dmbinder#9]
Hi !

I'm using this extensions for some days now (wonderful work by the way) and i'm currently trying to improve my layout. For this, i add a `style` tag at the beggining of the doc with my css. But even if it's working within https://homebrewery.naturalcrit.com/ it's not for the pdf rendering.

Any advice on how to make it work ?

PS. Not sure about how to post this but couldn't find a better place (please tell me if there is such and i'll move this right away).

**Comment by jsnee** [comment]
Thank you! I'm glad you can find it useful! I will say that there is some additional style I use on top of what is on the homebrewery site. So it is absolutely possible that the extension has some styles that might be overriding yours, but it should be easy to overcome/figure out what is going on. Also, this is absolutely the correct place to ask questions like that or provide feedback!

Can you provide an example of a style section that you might use (that doesn't seem to show up on the rendered PDF)?
Also, do you happen to know if it shows up on the markdown preview in VS Code (if you hit ctrl+k, v it should pop up a second window with a live preview of your document as it should be rendered)?

**Comment by Grimo0** [comment]
Since then i changed my brew and can't find the exact css i was applying but this one doesn't work : 
```css
<style>
.phb#p1 { text-align:center; }
.phb#p1:after { display:none; } 
</style>
```
This should hide the yellow line at the bottom of the first page.

It works within the preview though as you guessed.

By the way, i noticed why doing some tests two bugs with the `Automaticaly generate component blocks` function but i will post them under an other issue.

**Comment by jsnee** [comment]
I don't have any issues with this:
![image](https://user-images.githubusercontent.com/2386345/65975664-91610e00-e434-11e9-88ac-a8b79ca708db.png)

I'd ask three questions:
- Are you using the latest version of the extension? (Version 0.5.3)
- Do you have the PDF opened up when you try to render it? (I've had some issues where if I had the PDF open when I render a source file, it fails to overwrite the file since it's in use)
- Do you see any messages pop up in the bottom right hand corner when you try to render the file? (Might look like the image below)
![image](https://user-images.githubusercontent.com/2386345/65975986-177d5480-e435-11e9-86c5-02eca3da2a8e.png)

**Comment by Grimo0** [comment]
Didn't think about that, but it seems logic with the exposed setting.
Thank you for checking it !

**Comment by jsnee** [comment]
Fixes are in and Microsoft is in the process of verifying the updated extension, I'll close the other ticket once it goes live! Thanks again! And keep the feedback coming!
